repos:
  # Chequeos básicos de archivos
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: detect-private-key
      - id: forbid-submodules

  # Formateo Python
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.11

  # Linter Python (y formateo ruff)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Orden de imports Python
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Type-checking Python (opcional)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: []

  # Hooks locales para FE (sólo corren si hay package.json)
  - repo: local
    hooks:
      - id: eslint
        name: eslint (frontend)
        language: system
        pass_filenames: false
        entry: bash -lc 'if [ -f frontend/package.json ]; then (cd frontend && npx -y eslint .); elif [ -f package.json ]; then npx -y eslint .; else echo "skip eslint: no package.json"; fi'
        types_or: [javascript, jsx, ts, tsx]

      - id: prettier
        name: prettier -c (frontend)
        language: system
        pass_filenames: false
        entry: bash -lc 'if [ -f frontend/package.json ]; then (cd frontend && npx -y prettier -c .); elif [ -f package.json ]; then npx -y prettier -c .; else echo "skip prettier: no package.json"; fi'
        types_or: [javascript, jsx, ts, tsx, json, css, scss, md, yaml, yml]
